### ISSUE TITLE
Quoted column regex weirdness

### ISSUE THREAD

**Issue by chris5287** [barry-jones/csv-validator#12]
Looks like the Regex isn't a bit too capture happy :(

Example with the following input:
`somthing,before,\"just, a string\",seperated,after`

It actually returns:
![image](https://user-images.githubusercontent.com/1552744/84011139-9a17c580-a96d-11ea-9603-4e2e2d15c58e.png)

**Comment by barry-jones** [comment]
That is weird. Alright I will take a look at that tonight at some point hopefully.

**Comment by chris5287** [comment]
Looks like passing `RegexOptions.ExplicitCapture` to Regex.Split will fix it?

https://stackoverflow.com/questions/19286238/is-this-a-bug-in-nets-regex-split#answers-header

**Comment by barry-jones** [comment]
Thanks for heads up. Much appreciated. New version pushed with fix.
