### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by chris5287** [barry-jones/csv-validator#5]
Hi, this looks awesome.

Any chance of deploying as a NuGet package to use as a library within another application.

**Comment by barry-jones** [comment]
Hi! This is currently a CLI application, and is intended to be used from the command line either as part of a script or to perform ad-hoc validation of CSV files.

There is some scope for it to be imported and used inside another project. What are the use cases for needed to validate on disc files inside an another application. Just wondering to see how useful that functionality would be to everyone.

**Comment by chris5287** [comment]
I would use it for file validation on upload, so suspect this could be easily extended with Stream support (looks like you have an interface already but would be good to add async support). Otherwise you can just run dotnet pack to get the nuget package as is today :)

**Comment by barry-jones** [comment]
Thanks for the suggestion I will look in to it. Before I create a nuget package I would prefer to split the library portions out in to a netstandard dll and have the CLI seperate. Also creating a `StreamSource` to use instead of the `FileSource` would be beneficial.

In the meantime feel free to build and reference the library directly.

**Comment by barry-jones** [comment]
It is now available as a NuGet package. If you have any feedback on the API and usage I would love to hear it. Thanks.

https://www.nuget.org/packages/CsvValidator

**Comment by chris5287** [comment]
Awesome, I'll give it a test run later :)

I'll raise any feature request as separate issues, so I'll close this one out.

Thanks again for the effort!
